index.js
test.js

Currently, looking up an object at `path` will return `undefined`. The code recurses one time too many because `[].join('.')` is still a string. This fixes that.
``` js
dotProp({foo: {bar: 1}}, 'foo'); // undefined, should be {bar: 1}
```

Support returning an object

---

index.js
package.json
readme.md
test.js

Setter. While it is possible to impliment setter using recursion, it would not work with getter (`t.assert(dotProp(f1, 'foo', 2) === 2);` would fail).
It avoids recursion. I personally find recursive functions are hard to follow.
`dotProp({foo: {bar: a}}, foo.fake.fake2)` should throw a TypeError instead of returning `undefined`.
Use lodash to avoid reinventing the wheel.

Rewrite this module

---

index.js
test.js

Allows for passing in functions at the top level or setting properties on them when they're already in the object passed in

Treat functions as objects

---

index.js
test.js

Resolves #21 
This is using the existing semantics of `obj[prop] === undefined` but as mentioned in #23, maybe it should test `obj.hasOwnProperty`

Add has method

---

index.js
test.js

As far as I could make up from the conversation in #23, this might solve the issue.
If the property that is trying to be accessed, is non-enumerable, it will return `undefined`.

ignore non-enumerable properties - fixes #23

---

index.js
test.js

backslash in prop should work

---

index.js
test.js

do not throw if value is null

---

index.js
readme.md
test.js

This PR supersedes #30, which caused failures after merge due to newer code returning early.
---
This PR adds the ability to return a default value if the nested object path does not exist. 
It will still return `undefined`, by default, but now a user can supply a value to be returned instead.
A new test has been added and all existing tests pass.
The readme has also been updated with new examples and api explanation.

Add ability to return default value if path is undefined

---

index.js
readme.md
test.js

Just a small change to return the object from the `set` method. I find it convenient in some cases, and it does not add any significant overhead.
Feel free to merge if this makes sense to you. Tests and readme are updated accordingly.

Return object from the `.set()` method

---

index.d.ts
readme.md

e.g.
```
> dotProp.get(undefined, 'a')
undefined
> dotProp.get(undefined, 'a', 'b')
'b'
```

Allow specifying `undefined` as the object for `.get()` and `.has()`

---

test.js

Change `t.is(..., true)` to `t.true(...)` and `t.is(..., false)` to `t.false(...)`.

Simplify unit tests

---

index.d.ts
index.js
index.test-d.ts
readme.md
test.js

Make `.delete()` return a boolean

---

index.js
test.js

Changes the way to check property for enumerability, fixes #46

Allow getting non-enumerable properties

---

index.js
test.js

Fix an issue were the default value was not returned if the last part of the path was undefined.

Fix default value issue when last part of part of path is undefined

---

index.js
test.js

This is the last untested part of the code (#70)

Return default value if path is invalid

---

index.d.ts
index.js
readme.md
test.js

```js
import {getProperty, escapePath} from 'dot-prop';
const object = {
foo: {
bar: ['👸🏻 You found me Mario!'],
},
'foo.bar[0]' : '🍄 The princess is in another castle!',
};
const escapedPath = escapePath('foo.bar[0]');
console.log(getProperty(object, escapedPath));
//=> '🍄 The princess is in another castle!'
```
Fixes #83

Add `escapePath()`

---

index.js
test.js

Also avoids unnecessary allocation and set.
Fixes cases like the following:
```javascript
let obj = { a: [1,2] };
dotProp.delete(obj, 'a.1');
dotProp.set(obj, 'a.length', 1);
```
Previously would throw `Uncaught RangeError: Invalid array length` when it tries to set `obj.a.length = {}`

Fix crash when modifying array length

---

index.d.ts
index.js
index.test-d.ts
readme.md
test.js

Add `deepKeys()`

---

index.js
test.js

Sometimes, slashes work the same way whether they are escaped or not.
1. If a slash is added that doesn't change the behaviour of the proceeding character, the slash is interpreted literally.
2. If a slash escapes another slash, the pair is interpreted as a single slash.
The regex automatically doubles each backslash, transforming the first case into the second case. This has no semantic effect though is less space-efficient, as shown in other tests:
https://github.com/sindresorhus/dot-prop/blob/1794b86f5a8fbb135c6264ddfbc9c4a003c486ab/test.js#L21-L22
A regex lookahead could potentially improve this.

Improve tests

---

index.d.ts
index.js
readme.md
test.js

fix deepkeys to work with empty arrays and objects

---

index.js
readme.md
test.js

fix https://github.com/sindresorhus/dot-prop/issues/108 and https://github.com/sindresorhus/dot-prop/issues/109

fix deepkeys for sparsed arrays
